// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLDMAP.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NLDMAP.Infrastructure.Migrations
{
    [DbContext(typeof(NldmapDbContext))]
    partial class NldmapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NLDMAP.Domain.Entities.MissingPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Curp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasDisability")
                        .HasColumnType("boolean");

                    b.Property<string>("Height")
                        .HasColumnType("text");

                    b.Property<string>("IdentifyingSigns")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotographyUrl")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MissingPersons");
                });

            modelBuilder.Entity("NLDMAP.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ConsentUseExclusive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MissingPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MissingPersonId1")
                        .HasColumnType("uuid");

                    b.Property<string>("MissingPersonRelation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequestInformationPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MissingPersonId");

                    b.HasIndex("MissingPersonId1");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("NLDMAP.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlertRadioKm")
                        .HasColumnType("integer");

                    b.Property<bool>("BeAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("Curp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schooling")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<string>("SsoProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SsoProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NLDMAP.Domain.Entities.Report", b =>
                {
                    b.HasOne("NLDMAP.Domain.Entities.MissingPerson", null)
                        .WithMany()
                        .HasForeignKey("MissingPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NLDMAP.Domain.Entities.MissingPerson", null)
                        .WithMany("ReportHistory")
                        .HasForeignKey("MissingPersonId1");

                    b.HasOne("NLDMAP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("NLDMAP.Domain.ValueObjects.DisappearanceEvents", "Events", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Circumstance")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("EventsDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<TimeSpan>("EventsHour")
                                .HasColumnType("interval");

                            b1.Property<string>("FactsDescription")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.Property<string>("Municipality")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("ReporterPresent")
                                .HasColumnType("boolean");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ReportId");

                            b1.ToTable("Reports");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.Navigation("Events")
                        .IsRequired();
                });

            modelBuilder.Entity("NLDMAP.Domain.Entities.MissingPerson", b =>
                {
                    b.Navigation("ReportHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
